plugin: aws_ec2
regions:
  - ap-northeast-2
filters:
  # 특정 태그가 있는 인스턴스만 가져오도록 필터링
  instance-state-name: [ 'running' ]
  tag:Name:
    - "Roulette-Serverr" # 테라폼에서 지정한 Name 태그와 일치해야 함
hostnames:
  # 접속할 때 사용할 주소 (공인 IP 사용 시)
  - public-ip-address
compose:
  # 앤서블 접속 시 사용할 유저 설정 (예: ubuntu 또는 ec2-user)
  ansible_user: "'ubuntu'"